app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255),unique = True, index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    comments = db.relationship('Comment', backref='user', lazy="dynamic")
    posts = db.relationship('Post', backref='user', lazy = "dynamic")
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


    def __repr__(self):
        return f'User {self.username}'    

class Category(db.Model):
    __tablename__="categories"
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.String(255))


class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    post_id=db.Column(db.Integer,db.ForeignKey('posts.id'))
    comment_id = db.Column(db.Integer)
    pitch_comment = db.Column(db.String)
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    
   

   
    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    
    def get_comments(self):
        comments = Comment.query.all()
        return comments

    def get_comment(self):
        comment = Comment.query.filter_by(comment_id)
        return comment


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    text = db.Column(db.String(255))
    post_id = db.Column(db.Integer)
    category=db.Column(db.String(255))
    user_id=db.Column(db.Integer, db.ForeignKey('users.id'))
   
    
    comments=db.relationship('Comment', backref='posts', lazy='dynamic')


    def save_post(self):
        db.session.add(self)
        db.session.commit()


    def get_posts(self):
        posts = Post.query.all()
        return posts

    def get_post(self):
        post = Post.query.filter_by(post_id)
        return post

    
    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.validators import Required, Length


class PostForm(FlaskForm):
    CATEGORIES=[('SALES PITCH', 'SALES PITCH'), ('BUSINESS PITCH', 'BUSINESS PITCH'), ('MUSIC PITCH', 'MUSIC PITCH'), ('ELEVATOR PITCH', 'ELEVATOR PITCH')]
    category=SelectField("Categories",choices=CATEGORIES)
    post=TextAreaField("Post",validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('')
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask 
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

simple = SimpleMDE()
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos', IMAGES)

def create_app(config_name):
   
   app = Flask(__name__)
   
   #Creating the app configurations
   app.config.from_object(config_options[config_name])


   #configure UploadSet
   configure_uploads(app, photos)

   #Initializing Flask Extensions
   bootstrap.init_app(app)
   db.init_app(app)
   login_manager.init_app(app)
   mail.init_app(app)
   simple.init_app(app)

   # Registering the blueprint
   from .main import main as main_blueprint
   app.register_blueprint(main_blueprint)
   from .auth import auth as auth_blueprint
   app.register_blueprint(auth_blueprint, url_prefix='/authenticate')
    

   return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint( 'main' , __name__ )

from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for,abort
from flask_login import login_required
from . import main
from ..models import Comment, User, Post
from .forms import CommentForm, UpdateProfile, PostForm
from flask_login import login_required,current_user
from ..import db,photos


@main.route("/",methods=["GET","POST"])
def index():
    categories=["SALES PITCH", "BUSINESS PITCH", "MUSIC PITCH", "ELEVATOR PITCH"]
    return render_template('index.html',categories=categories)



@main.route("/pitches/<string:category>")
def posts(category):
    posts=list(Post.query.filter_by(category=category))
    return render_template("/pitches.html",posts=posts)



@main.route("/add",methods=["GET","POST"])
@login_required
def add():
    post_form=PostForm()
    if post_form.validate_on_submit():
        print(post_form.category.data)
        post=Post(text=post_form.post.data,category=post_form.category.data,user_id=current_user.id)
        post.save_post()
        return redirect(url_for("main.index"))
    return render_template('./add.html',post_form=post_form)



@main.route('/comment/new/<int:post_id>', methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    form = CommentForm()
    post = Post.query.filter_by(id=post_id).first()

    if form.validate_on_submit():
        comment = form.comment.data

        # Updated comment instance
        new_comment = Comment(pitch_comment=comment,user_id=current_user.id, post_id=post_id)

        # save review method
        db.session.add(new_comment)
        db.session.commit()
        
       
    all_comments = Comment.query.filter_by(post_id=post_id).all()
    
    return render_template('comment.html',form=form, comments=all_comments, post=post)




@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/add.html
{% extends "./base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {% if current_user.is_authenticated %}

    {% endif %}
    {{ wtf.quick_form(post_form) }}
    {% endblock %}
</div>

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{%block styles %}
{{super()}}
<!--Importing the simple mde css and js files  -->
{{ simplemde.css}}
{{ simplemde.js }}

{% endblock %}

app/templates/comment.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">{{post.category}}</div>
        <div class="panel-body">
            {{post.text}}
            <br>

        </div>
    </div>

    <p>COMMENTS</p>

    {% if comments %}
    {%for comment in comments%}
    <div class="panel panel-primary">
        <div class="panel-heading">{{comment.posted}}</div>
        <div class="panel-body">
            {{comment.pitch_comment}}
            <br>

        </div>
    </div>
    {% endfor %}
    {%endif%}
    <h3>comment</h3>
    {{ wtf.quick_form(form) }}

    {% endblock %}
</div>

app/templates/fourOwfour.html
 {% extends 'base.html'%}
 <div class="container">
     {% block content %}
     <h1>WHOOOPS we can't find that page</h1>
     {% endblock %}
 </div>

app/templates/index.html
{% extends "./base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


{% block content %}
<div class="container" style="margin-top:30px">
    <div class="page-header">
        <h3>Choose a pitch category</h3>
    </div>
    <div class="list-group">
        {% if current_user.is_authenticated %}
        <div class="container">
            <a class="btn btn-primary" href="{{url_for('main.add')}}">+ Add Pitch</a>
        </div>
        {% endif %}
        <div class="list-group" style="margin-top:30px">
            {% for category in categories %}
            <a href="/pitches/{{category}}" class="list-group-item list-group-item-action">{{category}}</a>
            {% endfor %}
        </div>

    </div>

    {% endblock %}
</div>

app/templates/navbar.html
 <div class="navbar navbar-inverse" role="navigation">
     <div class="container-fluid">
         <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="/"> Pitches </a>
         </div>
         <div class="navbar-collapse collapse">
             <ul class="nav navbar-nav">
                 <li><a href="/">Home</a></li>
         </div>
         <ul class="nav navbar-nav navbar-right">
             {% if current_user.is_authenticated %}
             <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
             <li style="color:white;padding:15px;">{{current_user.username}}</li>
             <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
             {% else %}
             <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
             {%endif%}
         </ul>
     </div>
 </div>

app/templates/new_comment.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
    Comment
    {{ wtf.quick_form(form) }}


    Comments
    {% for comment in comments %}

    {{comment.pitch_comment}}
    {% endfor %}
    {% endblock %}
</div>

app/templates/pitches.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


{% block content %}
<div class="container">
    <div class="jumbotron">
        <p>PITCHES</p>
    </div>
    {% if posts %}
    {% for post in posts %}

    <div class="panel panel-primary">
        <div class="panel-heading">{{post.category}}</div>
        <div class="panel-body">
            {{post.text}}
            <br>
            <br>
            <div>
                <div class=""><a href="{{url_for('main.new_comment',post_id =post.id)}}">Add a comment</div>
            </div>
        </div>
    </div>


    {% endfor %}
    {% else %}
    No post in this category yet !!
    {% endif %}

</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}

            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}

        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}